name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  tag:
    - 'v*'

jobs:
  # Job 1: Build and Lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Build application
        run: |
          cd web
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: web/dist
          retention-days: 7

  # Job 2: Run Tests
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Install Playwright
        run: |
          cd web
          npx playwright install --with-deps chromium firefox

      - name: Run tests
        run: |
          cd web
          npm test -- --reporter=list --max-failures=10
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: web/test-results/
          retention-days: 7

  # Job 3: Build Docker Image
  docker:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/'))
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker tags
        id: tags
        run: |
          TAGS=""
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAGS="cora-ai:latest,cora-ai:main"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            TAGS="cora-ai:develop"
          elif [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            TAGS="cora-ai:${VERSION},cora-ai:latest"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Save Docker image
        run: |
          docker save cora-ai:latest > cora-ai.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: cora-ai.tar
          retention-days: 7

  # Job 4: Security Scan
  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: |
          cd web
          npm ci

      - name: Run security audit
        run: |
          cd web
          npm audit --audit-level=moderate
        continue-on-error: true

      - name: Check for outdated packages
        run: |
          cd web
          npx npm-check-updates
        continue-on-error: true

  # Job 5: Release
  release:
    runs-on: ubuntu-latest
    needs: [build, test, docker, security]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: ./dist

      - name: Create release archive
        run: |
          tar -czf cora-ai-${{ github.ref_name }}.tar.gz dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cora-ai-${{ github.ref_name }}.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: false